language: python
sudo: true
services:
 - docker

python:
  - 3.6
  - 3.5
  - 3.4

# install dependencies
install:
  - ./travis/install-minikube.bash
  - ./kubectl version
  - pip install --no-cache-dir -e .
  - pip install --no-cache-dir jupyterhub-dummyauthenticator
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install -g configurable-http-proxy
  - jupyterhub

# command to run tests
script:
  - python setup.py test

matrix:
  fast_finish: true
