language: python
sudo: true
services:
 - docker

python:
  - 3.6
  - 3.5
  - 3.4

# install dependencies
install:
  - ./travis/install-minikube.bash
  - ./kubectl version
  - pip install --no-cache-dir -e .
  - pip install --no-cache-dir jupyterhub-dummyauthenticator
  - jupyterhub

# command to run tests
script:
  - python setup.py test

matrix:
  fast_finish: true
